name: Metrics

on:
  schedule:
    - cron: "0 0 * * 0" 
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin: repositories
          plugin_repositories: 100
