name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: arnavparekar
          UTC_OFFSET: 5.5
          TOKEN: ${{ secrets.PROFILE_CARDS_TOKEN }} 
